# Generated by Django 3.1 on 2020-08-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('position_header', models.CharField(blank=True, max_length=255, null=True)),
                ('position_sub_header', models.CharField(blank=True, max_length=255, null=True)),
                ('freelance', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'about',
            },
        ),
    ]
