# Generated by Django 3.1 on 2020-08-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_service_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
