# Generated by Django 3.1 on 2020-08-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='embed_map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
